/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Admin (void);
GtkWidget* create_list (void);
GtkWidget* create_add (void);
GtkWidget* create_activ (void);
GtkWidget* create_stats (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_Coach (void);
GtkWidget* create_seancecoach (void);
GtkWidget* create_window4 (void);
GtkWidget* create_Med (void);
GtkWidget* create_FicheMed (void);
GtkWidget* create_ListMed (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window7 (void);
GtkWidget* create_adh (void);
GtkWidget* create_adhoffres (void);
GtkWidget* create_calmed (void);
GtkWidget* create_ajmed (void);
GtkWidget* create_ListeMed2 (void);
GtkWidget* create_suppmed (void);
GtkWidget* create_modmed (void);
GtkWidget* create_consad (void);
GtkWidget* create_admed (void);
GtkWidget* create_adcoach (void);
GtkWidget* create_notcoach (void);
GtkWidget* create_adcur (void);
GtkWidget* create_adinscur (void);
GtkWidget* create_adent (void);
GtkWidget* create_adinsent (void);
GtkWidget* create_mod (void);
GtkWidget* create_edit_acc (void);
GtkWidget* create_activ_add (void);
GtkWidget* create_activ_edit (void);
GtkWidget* create_deals (void);
GtkWidget* create_deals_add (void);
GtkWidget* create_deals_edit (void);
GtkWidget* create_adhev (void);
GtkWidget* create_adinscev (void);
GtkWidget* create_modfiche (void);
GtkWidget* create_modifpass (void);
